#include <algorithm>
#include <array>
#include <cctype>
#include <chrono>
#include <concepts>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <vector>

#ifndef ENABLE_BENCHMARK
#  define ENABLE_BENCHMARK 1
#endif

#include "polyphaseiir.hpp"

// Includes the compile-time coefficients generated by Python
#include "coefficients.hpp"

// --- Lightweight JSON Parser & Lexer Implementation ---

enum class TokenType {
  LBrace,
  RBrace,
  LBracket,
  RBracket,
  Colon,
  Comma,
  String,
  Number,
  Boolean,
  Null,
  End
};

struct Token {
  TokenType type;
  std::string value;
};

class JsonLexer {
  std::string src;
  size_t pos = 0;

public:
  JsonLexer(std::string s) : src(std::move(s)) {}

  Token next() {
    while (pos < src.size() && std::isspace(src[pos])) { pos++; }
    if (pos >= src.size()) { return {TokenType::End, ""}; }
    char c = src[pos];
    if (c == '{') {
      pos++;
      return {TokenType::LBrace, "{"};
    }
    if (c == '}') {
      pos++;
      return {TokenType::RBrace, "}"};
    }
    if (c == '[') {
      pos++;
      return {TokenType::LBracket, "["};
    }
    if (c == ']') {
      pos++;
      return {TokenType::RBracket, "]"};
    }
    if (c == ':') {
      pos++;
      return {TokenType::Colon, ":"};
    }
    if (c == ',') {
      pos++;
      return {TokenType::Comma, ","};
    }
    if (c == '"') {
      pos++;
      std::string s;
      while (pos < src.size() && src[pos] != '"') {
        if (src[pos] == '\\') {
          pos++;
          if (pos < src.size()) { s += src[pos++]; }
        } else {
          s += src[pos++];
        }
      }
      if (pos < src.size()) { pos++; }
      return {TokenType::String, s};
    }
    if (std::isdigit(c) || c == '-' || c == '+' || c == '.') {
      std::string val;
      while (pos < src.size()
             && (std::isalnum(src[pos]) || src[pos] == '-' || src[pos] == '+' || src[pos] == '.')) {
        val += src[pos++];
      }
      return {TokenType::Number, val};
    }
    if (std::isalpha(c)) {
      std::string val;
      while (pos < src.size() && std::isalpha(src[pos])) { val += src[pos++]; }
      if (val == "true" || val == "false") { return {TokenType::Boolean, val}; }
      if (val == "null") { return {TokenType::Null, val}; }
    }
    throw std::runtime_error("Unexpected character in JSON: " + std::string(1, c));
  }
};

struct JsonValue {
  enum Type { Null, Bool, Number, String, Array, Object };
  Type type = Null;
  bool bool_val = false;
  double num_val = 0.0;
  std::string str_val;
  std::vector<JsonValue> arr_val;
  std::map<std::string, JsonValue> obj_val;

  bool is_null() const { return type == Null; }
  bool is_bool() const { return type == Bool; }
  bool is_num() const { return type == Number; }
  bool is_string() const { return type == String; }
  bool is_array() const { return type == Array; }
  bool is_object() const { return type == Object; }

  const JsonValue& operator[](const std::string& key) const {
    auto it = obj_val.find(key);
    if (it == obj_val.end()) { throw std::runtime_error("Key not found: " + key); }
    return it->second;
  }

  const JsonValue& operator[](size_t idx) const {
    if (idx >= arr_val.size()) { throw std::runtime_error("Index out of range"); }
    return arr_val[idx];
  }
};

class JsonParser {
  std::vector<Token> tokens;
  size_t pos = 0;

  Token peek() {
    if (pos < tokens.size()) { return tokens[pos]; }
    return {TokenType::End, ""};
  }

  Token consume() {
    Token t = peek();
    if (pos < tokens.size()) { pos++; }
    return t;
  }

public:
  JsonParser(std::vector<Token> t) : tokens(std::move(t)) {}

  JsonValue parse() {
    Token t = peek();
    if (t.type == TokenType::LBrace) {
      return parse_object();
    } else if (t.type == TokenType::LBracket) {
      return parse_array();
    } else if (t.type == TokenType::String) {
      consume();
      JsonValue val;
      val.type = JsonValue::String;
      val.str_val = t.value;
      return val;
    } else if (t.type == TokenType::Number) {
      consume();
      JsonValue val;
      val.type = JsonValue::Number;
      val.num_val = std::stod(t.value);
      return val;
    } else if (t.type == TokenType::Boolean) {
      consume();
      JsonValue val;
      val.type = JsonValue::Bool;
      val.bool_val = (t.value == "true");
      return val;
    } else if (t.type == TokenType::Null) {
      consume();
      JsonValue val;
      val.type = JsonValue::Null;
      return val;
    }
    throw std::runtime_error("Unexpected token in parser: " + t.value);
  }

private:
  JsonValue parse_array() {
    consume(); // [
    JsonValue val;
    val.type = JsonValue::Array;
    if (peek().type == TokenType::RBracket) {
      consume();
      return val;
    }
    while (true) {
      val.arr_val.push_back(parse());
      Token t = peek();
      if (t.type == TokenType::Comma) {
        consume();
      } else if (t.type == TokenType::RBracket) {
        consume();
        break;
      } else {
        throw std::runtime_error("Expected ',' or ']' in array, got: " + t.value);
      }
    }
    return val;
  }

  JsonValue parse_object() {
    consume(); // {
    JsonValue val;
    val.type = JsonValue::Object;
    if (peek().type == TokenType::RBrace) {
      consume();
      return val;
    }
    while (true) {
      Token t = peek();
      if (t.type != TokenType::String) {
        throw std::runtime_error("Expected string key in object, got: " + t.value);
      }
      std::string key = consume().value;
      Token col = peek();
      if (col.type != TokenType::Colon) {
        throw std::runtime_error("Expected ':' after key, got: " + col.value);
      }
      consume();
      val.obj_val[key] = parse();
      Token sep = peek();
      if (sep.type == TokenType::Comma) {
        consume();
      } else if (sep.type == TokenType::RBrace) {
        consume();
        break;
      } else {
        throw std::runtime_error("Expected ',' or '}' in object, got: " + sep.value);
      }
    }
    return val;
  }
};

JsonValue parse_json_file(const std::string& path) {
  std::ifstream f(path);
  if (!f.is_open()) { throw std::runtime_error("Could not open file: " + path); }
  std::stringstream ss;
  ss << f.rdbuf();
  std::string src = ss.str();

  JsonLexer lexer(src);
  std::vector<Token> tokens;
  while (true) {
    Token t = lexer.next();
    tokens.push_back(t);
    if (t.type == TokenType::End) { break; }
  }

  JsonParser parser(tokens);
  return parser.parse();
}

std::string double_to_string(double val) {
  std::ostringstream ss;
  ss << std::setprecision(17) << std::scientific << val;
  return ss.str();
}

std::string float_to_string(float val) {
  std::ostringstream ss;
  ss << std::setprecision(9) << std::scientific << val;
  return ss.str();
}

template<std::floating_point T, template<typename, typename> typename Filter,
         template<typename> typename Coeffs>
struct TestCase {
  using FilterType = Filter<T, Coeffs<T>>;
  FilterType filter;
  std::vector<T> output;
  std::vector<T> ir;
  std::string name;

#if ENABLE_BENCHMARK
  double benchmark_time_ms = 0.0;
  size_t benchmark_samples = 0;
#endif

  TestCase(std::string test_name) : name(std::move(test_name)) { filter.reset(); }

  void run(const std::vector<std::vector<double>>& inputs_d,
           const std::vector<std::vector<float>>& inputs_f, size_t n_sample) {
    filter.reset();
    output.clear();
    output.reserve(n_sample);

    constexpr std::size_t M = Coefficients::Hybrid<double>::nPhase;

    for (size_t n = 0; n < n_sample; ++n) {
      std::array<T, M> frame;
      for (size_t k = 0; k < M; ++k) {
        if constexpr (std::is_same_v<T, double>) {
          frame[k] = inputs_d[k][n];
        } else {
          frame[k] = inputs_f[k][n];
        }
      }
      output.push_back(filter.process(frame));
    }
  }

  void run_ir(size_t ir_length) {
    filter.reset();
    ir.clear();
    ir.resize(ir_length, T(0));

    constexpr std::size_t M = Coefficients::Hybrid<double>::nPhase;
    if (ir_length % M != 0) {
      throw std::runtime_error("ir_length must be a multiple of the decimation factor M");
    }
    size_t n_frames = ir_length / M;

    // Linearly reconstruct the LTI high-rate impulse response phase-by-phase.
    for (std::size_t j = 0; j < M; ++j) {
      filter.reset();
      for (size_t m = 0; m < n_frames; ++m) {
        std::array<T, M> frame{}; // Zero-initialized
        if (m == 0) {
          frame[j] = T(1); // Set impulse at phase index j
        }
        T y = filter.process(frame);
        ir[m * M + j] = y;
      }
    }
  }

#if ENABLE_BENCHMARK
  void run_benchmark(const std::vector<std::vector<double>>& inputs_d,
                     const std::vector<std::vector<float>>& inputs_f, size_t n_sample) {
    filter.reset();
    constexpr std::size_t M = Coefficients::Hybrid<double>::nPhase;

    std::vector<std::array<T, M>> frames(n_sample);
    for (size_t n = 0; n < n_sample; ++n) {
      for (size_t k = 0; k < M; ++k) {
        if constexpr (std::is_same_v<T, double>) {
          frames[n][k] = inputs_d[k][n];
        } else {
          frames[n][k] = inputs_f[k][n];
        }
      }
    }

    // Warm-up run to establish cache residency
    for (size_t n = 0; n < n_sample; ++n) {
      T tmp = filter.process(frames[n]);
      (void)tmp;
    }
    filter.reset();

    const size_t total_samples = 1000000;
    const size_t iterations = total_samples / n_sample;
    benchmark_samples = iterations * n_sample;

    auto start = std::chrono::high_resolution_clock::now();
    T checksum = 0;
    for (size_t iter = 0; iter < iterations; ++iter) {
      for (size_t n = 0; n < n_sample; ++n) { checksum += filter.process(frames[n]); }
    }
    auto end = std::chrono::high_resolution_clock::now();

    // Prevent compiler from optimizing the loops away
    volatile T sink = checksum;
    (void)sink;

    std::chrono::duration<double, std::milli> duration = end - start;
    benchmark_time_ms = duration.count();
  }
#endif

  void write(std::ostream& out_file, bool comma) const {
    auto to_json_str = [&](std::string key, const std::vector<T>& y) {
      out_file << "  \"" << key << "\": [\n";
      for (size_t i = 0; i < y.size(); ++i) {
        out_file << "    \"";
        if constexpr (std::is_same_v<T, double>) {
          out_file << double_to_string(y[i]);
        } else {
          out_file << float_to_string(y[i]);
        }
        out_file << "\"";
        if (i + 1 < y.size()) { out_file << ","; }
        out_file << "\n";
      }
      out_file << "  ]";
    };

    to_json_str(name + "_noise", output);
    out_file << ",\n";

    to_json_str(name + "_ir", ir);
    out_file << (comma ? "," : "") << "\n";
  }
};

// --- Runner Entry Point ---

int main(int argc, char* argv[]) {
  namespace Co = Coefficients;

  if (argc < 3) {
    std::cerr << "Usage: " << argv[0] << " <reference.json> <results.json>\n";
    return 1;
  }
  std::string ref_path = argv[1];
  std::string res_path = argv[2];

  try {
    auto test_cases = std::make_tuple(
      TestCase<double, TDF2::SosFilter_fma, Co::SerialSos>("tdf2_f64"),
      TestCase<float, TDF2::SosFilter_fma, Co::SerialSos>("tdf2_f32"),
      TestCase<double, Simple_fma::PolyphaseIir, Co::Hybrid>("hybrid_simple_f64"),
      TestCase<float, Simple_fma::PolyphaseIir, Co::Hybrid>("hybrid_simple_f32"),
      TestCase<double, KahanSum_fma::PolyphaseIir, Co::Hybrid>("hybrid_kahan_f64"),
      TestCase<float, KahanSum_fma::PolyphaseIir, Co::Hybrid>("hybrid_kahan_f32"),
      TestCase<double, SosSimple::PolyphaseIirSos, Co::PolyphaseSos>("sos_simple_f64"),
      TestCase<float, SosSimple::PolyphaseIirSos, Co::PolyphaseSos>("sos_simple_f32"),
      TestCase<double, SosKahanSum::PolyphaseIirSos, Co::PolyphaseSos>("sos_kahan_f64"),
      TestCase<float, SosKahanSum::PolyphaseIirSos, Co::PolyphaseSos>("sos_kahan_f32"),
      TestCase<double, SosSimple2::PolyphaseIirSos, Co::PolyphaseSos2>("sos2_simple_f64"),
      TestCase<float, SosSimple2::PolyphaseIirSos, Co::PolyphaseSos2>("sos2_simple_f32"),
      TestCase<double, SosKahanSum2::PolyphaseIirSos, Co::PolyphaseSos2>("sos2_kahan_f64"),
      TestCase<float, SosKahanSum2::PolyphaseIirSos, Co::PolyphaseSos2>("sos2_kahan_f32"));

    JsonValue ref = parse_json_file(ref_path);

    int M = static_cast<int>(ref["M"].num_val);
    if (M != Co::Hybrid<double>::nPhase) {
      std::cerr << "Error: Decimation factor M in JSON (" << M
                << ") does not match compile-time nPhase (" << Co::Hybrid<double>::nPhase << ")\n";
      return 1;
    }

    // Noise.
    const auto& inputs_arr = ref["inputs"];
    size_t n_sample = inputs_arr[0].arr_val.size();

    std::vector<std::vector<double>> inputs_d(M, std::vector<double>(n_sample));
    std::vector<std::vector<float>> inputs_f(M, std::vector<float>(n_sample));

    for (int k = 0; k < M; ++k) {
      for (size_t n = 0; n < n_sample; ++n) {
        double val = std::stod(inputs_arr[k][n].str_val);
        inputs_d[k][n] = val;
        inputs_f[k][n] = static_cast<float>(val);
      }
    }

    std::apply([&](auto&... tc) { (tc.run(inputs_d, inputs_f, n_sample), ...); }, test_cases);

    // Impulse response.
    size_t ir_length = ref["impulse_response"].arr_val.size();
    std::apply([&](auto&... tc) { (tc.run_ir(ir_length), ...); }, test_cases);

#if ENABLE_BENCHMARK
    std::apply([&](auto&... tc) { (tc.run_benchmark(inputs_d, inputs_f, n_sample), ...); },
               test_cases);
#endif

    std::ofstream out_file(res_path);
    if (!out_file.is_open()) {
      std::cerr << "Could not open output file: " << res_path << "\n";
      return 1;
    }

    out_file << "{\n";

    std::apply(
      [&](const auto&... tc) {
        size_t idx = 0;
        size_t num_cases = sizeof...(tc);
        auto write_one = [&](const auto& t) {
          t.write(out_file, idx + 1 < num_cases || ENABLE_BENCHMARK);
          idx++;
        };
        (write_one(tc), ...);
      },
      test_cases);

#if ENABLE_BENCHMARK
    out_file << "  \"benchmarks\": {\n";
    std::apply(
      [&](const auto&... tc) {
        size_t idx = 0;
        size_t num_cases = sizeof...(tc);
        auto write_bench_one = [&](const auto& t) {
          out_file << "    \"" << t.name << "\": {\n";
          out_file << "      \"time_ms\": " << t.benchmark_time_ms << ",\n";
          out_file << "      \"num_samples\": " << t.benchmark_samples << ",\n";
          out_file << "      \"ns_per_sample\": "
                   << (t.benchmark_time_ms * 1e6 / t.benchmark_samples) << "\n";
          out_file << "    }" << (idx + 1 < num_cases ? "," : "") << "\n";
          idx++;
        };
        (write_bench_one(tc), ...);
      },
      test_cases);
    out_file << "  }\n";
#endif

    out_file << "}\n";

  } catch (const std::exception& e) {
    std::cerr << "Error: " << e.what() << "\n";
    return 1;
  }

  return 0;
}
