exclude:
- 3pole_lowpass/3pole_lowpass.md
- README.md
- _stab/choir.md
- _stab/energy_decay_curve.md
- _stab/nonliner_acoustics.md
- _stab/waveequation_parameters.md
- _stab/wavefunction.md
- am_pitchshift/am_pitchshift.md
- basic_fir/basic_fir.md
- burgers_exact/burgers_exact.md
- burgers_exact/demo/README.md
- burgers_godunov/burgers_godunov.md
- control_rate_interpolation/control_rate_interpolation.md
- convolution_without_latency/convolution_without_latency.md
- delay/delay.md
- double_ema_filter/double_ema_filter.md
- doublefilter/doublefilter.md
- downsampling/_dump/note.md
- downsampling/_dump/oversampling.md
- downsampling/_dump/polyphase_iir.md
- downsampling/_dump/remez.md
- downsampling/_dump/test.md
- downsampling/code/cpp/decimation/vcpkg.md
- downsampling/downsampling.md
- dr110_cymbal/demo/README.md
- dr110_cymbal/dr110_cymbal.md
- exponential_envelope/exponential_envelope.md
- exppoly_envelope/exppoly_envelope.md
- feedback_delay_network/cpp/README.md
- feedback_delay_network/feedback_delay_network.md
- fractional_delay_filter_socp/fractional_delay_filter_socp.md
- gibbs/gibbs.md
- golly_generations_clustering/demo/README.md
- golly_generations_clustering/gallery.md
- golly_generations_clustering/golly_generations_clustering.md
- grunwald_letnikov/demo/README.md
- grunwald_letnikov/grunwald_letnikov.md
- heat_wave_equation/demo/README.md
- heat_wave_equation/heat_wave_equation.md
- iir_halfband_decimator/_dump/hiir-designer/README.md
- iir_halfband_decimator/_dump/hiir.md
- iir_halfband_decimator/cpp/build_instruction.md
- iir_halfband_decimator/iir_halfband_decimator.md
- lfo_temposync/_dump/memo.md
- lfo_temposync/lfo_temposync.md
- limiter/_dump/graphviz/graphviz.md
- limiter/_dump/limiter.md
- limiter/_dump/limiter_gainhold.md
- limiter/_dump/limiter_old.md
- limiter/_dump/limiter_recipe.md
- limiter/_dump/musicdsp_lookahead_limiter.md
- limiter/_dump/soft_limiter.md
- limiter/_dump/tex_tikz/tikz.md
- limiter/_dump/vcpkg.md
- limiter/limiter.md
- limiter/musicdsp_lookahead_limiter.md
- linear_and_cubic_interpolation/linear_and_cubic_interpolation.md
- linear_envelope/linear_envelope.md
- ndboct/ndboct.md
- one_sec_sounds_clustering/one_sec_sounds_clustering.md
- parabolic_envelope/parabolic_envelope.md
- parabolic_envelope/parabolic_envelope_exp.md
- peak_hold_envelope/_dump/hold_backward.md
- peak_hold_envelope/peak_hold_envelope.md
- pitch_estimation/pitch_estimation.md
- pitch_estimation/plot_gallery_pitch_estimation.md
- polyblamp_residual/polyblamp_residual.md
- polyblep_residual/polyblep_residual.md
- ptr_oscillator/ptr_maxima.md
- ptr_oscillator/ptr_oscillator.md
- ptr_trapezoid/ptr_trapezoid.md
- resonant_one_pole_filter/code/README.md
- resonant_one_pole_filter/resonant_one_pole_filter.md
- s_curve_step_response_filter/s_curve_step_response_filter.md
- stereo_panning/stereo_panning.md
- truepeak_computation/_dump/note.md
- truepeak_computation/_dump/truepeak_old.md
- truepeak_computation/code/README.md
- truepeak_computation/code/cpp/benchmark/vcpkg.md
- truepeak_computation/code/data/dataset.md
- truepeak_computation/code/thiran_allpass/thiran.md
- truepeak_computation/truepeak_computation.md
- waveequation/waveequation.md
- waveequation2d/waveequation2d.md
- waveequation_fractional_zener/demo/README.md
- waveequation_fractional_zener/waveequation_fractional_zener.md
- waveequation_newmark_beta/waveequation_newmark_beta.md
- waveequationimplicit/demo/README.md
- waveequationimplicit/waveequationimplicit.md
- wavetable/wavetable.md
- wavetable_pitchbend/cpp/bench/license/LICENSE.md
- wavetable_pitchbend/cpp/bench/license/pocketfft/LICENSE.md
- wavetable_pitchbend/wavetable_pitchbend.md
